# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '**/Inshapardaz.Api/appsettings.json'
      env:
        AppSettings.DefaultConnection: ${{ secrets.CONNECTIONSTRING }}
        AppSettings.Allowed_Origins: ${{ secrets.ALLOWEDORIGINS }}

    - name: Build
      run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -r win-x86 -o ./Release ./src/Nawishta.Web/Nawishta.Web.csproj

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.DEPLOY_FTP_SERVER }}
        username: ${{ secrets.DEPLOY_FTP_USERNAME }}
        password: ${{ secrets.DEPLOY_FTP_PASSWORD }}
        server-dir: /dictionaries/
        local-dir: ./Release/